from turtle import *

def window():
    color("blue")
    begin_fill()
    for x in range(4):
        forward(10)
        right(90)
    end_fill()
def home():
    color("orange")
    begin_fill()
    forward(50)
    right(90)
    forward(100)
    right(90)
    forward(50)
    right(90)
    forward(100)
    right(90)
    end_fill()
def windows(x,y):
    for i in range(4):
        penup()
        goto(x, y)
        pendown()
        window()
        penup()
        goto(x+20, y)
        pendown()
        window()
        y -= 20

color("green")
speed(1000)
width(1000)
forward(1)
backward(1)
width(1)
home()
windows(10, -10)
penup()
goto(-100,0)
pendown()
home()
windows(-90, -10)
penup()
goto(-200,0)
pendown()
home()
windows(-190, -10)
penup()
goto(100,0)
pendown()
home()
windows(110, -10)
penup()
goto(200,0)
pendown()
home()
windows(210, -10)
penup()
goto(-300,140)
width(200)
pendown()
r = input()
if(r == "day"):
    color("light blue")
elif (r == "night"):
    color("indigo")
else:
    color("grey")
forward(600)
penup()
goto(-200,-100)
width(10)
color("black")
pendown()
forward(450)
if(r == "day"):
    penup()
    goto(-250,140)
    width(1)
    color("yellow")
    pendown()
    begin_fill()
    for a in range(18):
        forward(50)
        right(100)
    end_fill()
elif(r == "night"):
    penup()
    goto(-250,140)
    width(1)
    color("grey")
    pendown()
    begin_fill()
    for a in range(5):
        forward(50)
        right(144)
    end_fill()
    penup()
    goto(-210,140)
    width(1)
    color("yellow")
    pendown()
    begin_fill()
    for a in range(18):
        forward(50)
        right(100)
    end_fill()
    penup()
    goto(-170,140)
    width(1)
    color("yellow")
    pendown()
    begin_fill()
    for a in range(18):
        forward(50)
        right(100)
    end_fill()
penup()
color("black")
width(5)
goto(-25,-100)
pendown()
left(90)
forward(10)
backward(10)
right(90)
forward(100)
left(90)
forward(10)
backward(10)
exitonclick()